//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""184dadb1-a983-4c36-b667-e06cbd39ca84"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""da39e9e9-ab0d-41e5-9cdd-42954f978706"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""3a102b36-4dd1-4cef-8f79-008893b75589"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InteractAlternate"",
                    ""type"": ""Button"",
                    ""id"": ""897c0467-765e-4e76-a916-ba84c798eab4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""33d68adf-ce70-4caa-9d4a-bb4d4a857ea8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SumSkinSelect"",
                    ""type"": ""Button"",
                    ""id"": ""7c19386a-9047-45ea-9a14-5eac4c50b45f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SubSkinSelect"",
                    ""type"": ""Button"",
                    ""id"": ""65a62afd-b0e6-4ba0-b335-a883242539a9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""623a69f9-20a7-4def-a111-fe5723be6e6f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move_2"",
                    ""type"": ""Value"",
                    ""id"": ""fd97ecf3-f4e7-4e06-882e-fea5a29f046d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact_2"",
                    ""type"": ""Button"",
                    ""id"": ""8ac25d55-bf05-4b40-8c30-291a09a330e0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InteractAlternate_2"",
                    ""type"": ""Button"",
                    ""id"": ""428fc881-1bbf-4284-a15b-e5400074322d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash_2"",
                    ""type"": ""Button"",
                    ""id"": ""c57ea5e8-bd0b-49ba-a362-752ebeb23fae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SumSkinSelect_2"",
                    ""type"": ""Button"",
                    ""id"": ""e1b28090-3b95-4174-9d18-b941a4c64e86"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SubSkinSelect_2"",
                    ""type"": ""Button"",
                    ""id"": ""118c38f6-f497-43f4-a689-8ae19669097a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""2cc72034-4555-4030-8d5b-213057c55a30"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1df3d443-92a8-4930-8504-ec6edde7eeae"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""476dcaeb-8203-4d6a-9a1a-a40004c036e8"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5f444d03-c3dd-4391-9289-1450446c580f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1be4c548-97f3-40bc-8a7a-077a5865ad05"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1b3ee402-5b9d-44c5-a8d8-e17b9bdcffd0"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone(min=0.5)"",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a5c66a4-7d2b-41d0-8a8f-ad5ef489dd35"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b812fdcc-548a-4611-b372-d571e8128065"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5e12fad-59e4-47f7-9f96-f97c84d2e30f"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""56c96e4a-25ab-4e9b-91d2-7852326daa23"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractAlternate_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Arrow Keys"",
                    ""id"": ""d95c13c9-f9b9-43a3-a949-c2a453c23213"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move_2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0ec25813-4fb4-4c6b-b8ac-dc324849e804"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""263c9dad-0efb-4293-9ad5-5dfd0405f24d"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""18ba0f99-4f77-46be-a05f-f6caefe9ea02"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""80f3c49e-91cc-4c47-adb6-0b553f495375"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0352378e-6be6-463d-868c-0243ccb6c378"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractAlternate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7cac1a0c-990b-4d14-9e2c-c1eb6f102342"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractAlternate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1231af31-4cb7-4456-9f10-3ec691204e26"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f77e1ad9-f1ad-4c3a-931e-a8b4998e0c6c"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b0f15ca-1219-4fab-adc5-e48c6e139cfe"",
                    ""path"": ""<Keyboard>/rightCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""afa80203-f8f7-4b39-adf5-a6f168d94e47"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""55a7ab9b-ec23-4dc5-999f-1ec30c7ca556"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SubSkinSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""36d8be35-f064-49cb-9c5e-2f056871e1cf"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SubSkinSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f89dc7be-8bf6-4c28-9736-c52c59182580"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SubSkinSelect_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""28f86d74-61d0-482c-a242-53376bd4c278"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SumSkinSelect_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d013a78-db1d-487b-881a-5948f3b5ecf3"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SumSkinSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""26c66b26-256b-4c37-a0a4-585acbdf6a67"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SumSkinSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Interact = m_Player.FindAction("Interact", throwIfNotFound: true);
        m_Player_InteractAlternate = m_Player.FindAction("InteractAlternate", throwIfNotFound: true);
        m_Player_Dash = m_Player.FindAction("Dash", throwIfNotFound: true);
        m_Player_SumSkinSelect = m_Player.FindAction("SumSkinSelect", throwIfNotFound: true);
        m_Player_SubSkinSelect = m_Player.FindAction("SubSkinSelect", throwIfNotFound: true);
        m_Player_Pause = m_Player.FindAction("Pause", throwIfNotFound: true);
        m_Player_Move_2 = m_Player.FindAction("Move_2", throwIfNotFound: true);
        m_Player_Interact_2 = m_Player.FindAction("Interact_2", throwIfNotFound: true);
        m_Player_InteractAlternate_2 = m_Player.FindAction("InteractAlternate_2", throwIfNotFound: true);
        m_Player_Dash_2 = m_Player.FindAction("Dash_2", throwIfNotFound: true);
        m_Player_SumSkinSelect_2 = m_Player.FindAction("SumSkinSelect_2", throwIfNotFound: true);
        m_Player_SubSkinSelect_2 = m_Player.FindAction("SubSkinSelect_2", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Interact;
    private readonly InputAction m_Player_InteractAlternate;
    private readonly InputAction m_Player_Dash;
    private readonly InputAction m_Player_SumSkinSelect;
    private readonly InputAction m_Player_SubSkinSelect;
    private readonly InputAction m_Player_Pause;
    private readonly InputAction m_Player_Move_2;
    private readonly InputAction m_Player_Interact_2;
    private readonly InputAction m_Player_InteractAlternate_2;
    private readonly InputAction m_Player_Dash_2;
    private readonly InputAction m_Player_SumSkinSelect_2;
    private readonly InputAction m_Player_SubSkinSelect_2;
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Interact => m_Wrapper.m_Player_Interact;
        public InputAction @InteractAlternate => m_Wrapper.m_Player_InteractAlternate;
        public InputAction @Dash => m_Wrapper.m_Player_Dash;
        public InputAction @SumSkinSelect => m_Wrapper.m_Player_SumSkinSelect;
        public InputAction @SubSkinSelect => m_Wrapper.m_Player_SubSkinSelect;
        public InputAction @Pause => m_Wrapper.m_Player_Pause;
        public InputAction @Move_2 => m_Wrapper.m_Player_Move_2;
        public InputAction @Interact_2 => m_Wrapper.m_Player_Interact_2;
        public InputAction @InteractAlternate_2 => m_Wrapper.m_Player_InteractAlternate_2;
        public InputAction @Dash_2 => m_Wrapper.m_Player_Dash_2;
        public InputAction @SumSkinSelect_2 => m_Wrapper.m_Player_SumSkinSelect_2;
        public InputAction @SubSkinSelect_2 => m_Wrapper.m_Player_SubSkinSelect_2;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @InteractAlternate.started += instance.OnInteractAlternate;
            @InteractAlternate.performed += instance.OnInteractAlternate;
            @InteractAlternate.canceled += instance.OnInteractAlternate;
            @Dash.started += instance.OnDash;
            @Dash.performed += instance.OnDash;
            @Dash.canceled += instance.OnDash;
            @SumSkinSelect.started += instance.OnSumSkinSelect;
            @SumSkinSelect.performed += instance.OnSumSkinSelect;
            @SumSkinSelect.canceled += instance.OnSumSkinSelect;
            @SubSkinSelect.started += instance.OnSubSkinSelect;
            @SubSkinSelect.performed += instance.OnSubSkinSelect;
            @SubSkinSelect.canceled += instance.OnSubSkinSelect;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @Move_2.started += instance.OnMove_2;
            @Move_2.performed += instance.OnMove_2;
            @Move_2.canceled += instance.OnMove_2;
            @Interact_2.started += instance.OnInteract_2;
            @Interact_2.performed += instance.OnInteract_2;
            @Interact_2.canceled += instance.OnInteract_2;
            @InteractAlternate_2.started += instance.OnInteractAlternate_2;
            @InteractAlternate_2.performed += instance.OnInteractAlternate_2;
            @InteractAlternate_2.canceled += instance.OnInteractAlternate_2;
            @Dash_2.started += instance.OnDash_2;
            @Dash_2.performed += instance.OnDash_2;
            @Dash_2.canceled += instance.OnDash_2;
            @SumSkinSelect_2.started += instance.OnSumSkinSelect_2;
            @SumSkinSelect_2.performed += instance.OnSumSkinSelect_2;
            @SumSkinSelect_2.canceled += instance.OnSumSkinSelect_2;
            @SubSkinSelect_2.started += instance.OnSubSkinSelect_2;
            @SubSkinSelect_2.performed += instance.OnSubSkinSelect_2;
            @SubSkinSelect_2.canceled += instance.OnSubSkinSelect_2;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @InteractAlternate.started -= instance.OnInteractAlternate;
            @InteractAlternate.performed -= instance.OnInteractAlternate;
            @InteractAlternate.canceled -= instance.OnInteractAlternate;
            @Dash.started -= instance.OnDash;
            @Dash.performed -= instance.OnDash;
            @Dash.canceled -= instance.OnDash;
            @SumSkinSelect.started -= instance.OnSumSkinSelect;
            @SumSkinSelect.performed -= instance.OnSumSkinSelect;
            @SumSkinSelect.canceled -= instance.OnSumSkinSelect;
            @SubSkinSelect.started -= instance.OnSubSkinSelect;
            @SubSkinSelect.performed -= instance.OnSubSkinSelect;
            @SubSkinSelect.canceled -= instance.OnSubSkinSelect;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @Move_2.started -= instance.OnMove_2;
            @Move_2.performed -= instance.OnMove_2;
            @Move_2.canceled -= instance.OnMove_2;
            @Interact_2.started -= instance.OnInteract_2;
            @Interact_2.performed -= instance.OnInteract_2;
            @Interact_2.canceled -= instance.OnInteract_2;
            @InteractAlternate_2.started -= instance.OnInteractAlternate_2;
            @InteractAlternate_2.performed -= instance.OnInteractAlternate_2;
            @InteractAlternate_2.canceled -= instance.OnInteractAlternate_2;
            @Dash_2.started -= instance.OnDash_2;
            @Dash_2.performed -= instance.OnDash_2;
            @Dash_2.canceled -= instance.OnDash_2;
            @SumSkinSelect_2.started -= instance.OnSumSkinSelect_2;
            @SumSkinSelect_2.performed -= instance.OnSumSkinSelect_2;
            @SumSkinSelect_2.canceled -= instance.OnSumSkinSelect_2;
            @SubSkinSelect_2.started -= instance.OnSubSkinSelect_2;
            @SubSkinSelect_2.performed -= instance.OnSubSkinSelect_2;
            @SubSkinSelect_2.canceled -= instance.OnSubSkinSelect_2;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnInteractAlternate(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnSumSkinSelect(InputAction.CallbackContext context);
        void OnSubSkinSelect(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnMove_2(InputAction.CallbackContext context);
        void OnInteract_2(InputAction.CallbackContext context);
        void OnInteractAlternate_2(InputAction.CallbackContext context);
        void OnDash_2(InputAction.CallbackContext context);
        void OnSumSkinSelect_2(InputAction.CallbackContext context);
        void OnSubSkinSelect_2(InputAction.CallbackContext context);
    }
}
